source 'https://rubygems.org'

gem 'rails', '4.0.0'
gem 'sqlite3'

gem 'sass-rails', '~> 4.0.0'

gem 'uglifier', '>= 1.3.0'

gem 'coffee-rails', '~> 4.0.0'
gem 'jquery-rails'

gem 'turbolinks'

gem 'jbuilder', '~> 1.2'

group :test do 
  gem 'cucumber-rails', :require => false
  gem 'rspec-rails'
  gem 'database_cleaner'
end

group :doc do
  gem 'sdoc', require: false
end
