source 'https://rubygems.org'

gem 'rails', '3.2.14'

gem 'sqlite3'

group :test, :development do 
  gem 'rspec-rails'
  gem 'cucumber-rails', :require => false
  gem 'database_cleaner', '<= 1.0.3'
  gem 'pry'
end

group :assets do
  gem 'sass-rails',   '~> 3.2.3'
  gem 'coffee-rails', '~> 3.2.1'
  gem 'uglifier', '>= 1.0.3'
end

gem 'jquery-rails'
